<script setup lang="ts">
import { ref } from 'vue'
import { useRoute } from 'vue-router'
import {
  organization,
  socialLinks,
  mailtoHref,
  copyrightLine,
} from 'src/config/organization'

const route = useRoute()
const leftDrawerOpen = ref(false)
const org = organization

const navLinks = [
  { label: 'Home', to: '/', icon: 'home' },
  { label: 'About', to: '/about', icon: 'info' },
  { label: 'Schedule', to: '/schedule', icon: 'event' },
  { label: 'Announcements', to: '/announcements', icon: 'campaign' },
  { label: 'Contact', to: '/contact', icon: 'mail' },
]

function toggleDrawer() {
  leftDrawerOpen.value = !leftDrawerOpen.value
}

function isActive(to: string) {
  return to === '/' ? route.path === '/' : route.path.startsWith(to)
}
</script>

<template>
  <q-layout view="hHh Lpr lFf">
    <!-- Top Navigation -->
    <q-header class="site-header">
      <q-toolbar class="site-toolbar page-shell">
        <!-- Brand -->
        <router-link to="/" class="brand-link" :aria-label="`${org.identity.name} home`">
          <!-- public/ is served from the web root, so this path is absolute.
               The -white variant is the mono knockout mark for dark surfaces;
               both variants are generated by design/build_logo.py. -->
          <img
            src="/assets/JTWC-white-192.png"
            alt=""
            class="brand-logo"
          />
          <span class="brand-text">
            <span class="brand-text__main">{{ org.identity.brandLine1 }}</span>
            <span class="brand-text__sub">{{ org.identity.brandLine2 }}</span>
          </span>
        </router-link>

        <q-space />

        <!-- Desktop nav. Quasar's gt-sm is width-based; the previous
             .desktop-only / .mobile-only pair collided with Quasar's platform
             classes of the same name and hid navigation entirely on narrow
             windows. -->
        <nav class="gt-sm desktop-nav">
          <router-link
            v-for="link in navLinks"
            :key="link.to"
            :to="link.to"
            class="nav-link tap-target"
            :class="{ 'nav-link--active': isActive(link.to) }"
          >
            {{ link.label }}
          </router-link>

          <q-btn
            to="/admin"
            unelevated
            no-caps
            class="admin-btn q-ml-sm"
            label="Admin"
            icon="admin_panel_settings"
          />
        </nav>

        <!-- Mobile hamburger -->
        <q-btn
          flat
          round
          dense
          icon="menu"
          color="white"
          size="md"
          class="lt-md"
          aria-label="Open navigation menu"
          @click="toggleDrawer"
        />
      </q-toolbar>
    </q-header>

    <!-- Mobile Drawer -->
    <q-drawer
      v-model="leftDrawerOpen"
      side="right"
      overlay
      behavior="mobile"
      :width="284"
    >
      <div class="drawer-head">
        <img src="/assets/JTWC-white-192.png" alt="" class="drawer-logo" />
        <div>
          <div class="drawer-head__main">{{ org.identity.brandLine1 }}</div>
          <div class="drawer-head__sub">{{ org.identity.brandLine2 }}</div>
        </div>
      </div>

      <q-list padding>
        <q-item
          v-for="link in navLinks"
          :key="link.to"
          :to="link.to"
          clickable
          v-ripple
          class="drawer-item"
          active-class="drawer-item--active"
          @click="leftDrawerOpen = false"
        >
          <q-item-section avatar>
            <q-icon :name="link.icon" />
          </q-item-section>
          <q-item-section>{{ link.label }}</q-item-section>
        </q-item>

        <q-separator class="q-my-sm" />

        <q-item
          to="/admin"
          clickable
          v-ripple
          class="drawer-item"
          @click="leftDrawerOpen = false"
        >
          <q-item-section avatar>
            <q-icon name="admin_panel_settings" />
          </q-item-section>
          <q-item-section>Admin Login</q-item-section>
        </q-item>
      </q-list>
    </q-drawer>

    <!-- Page Content -->
    <q-page-container>
      <router-view />
    </q-page-container>

    <!-- Footer -->
    <footer class="site-footer">
      <div class="page-shell footer-grid">
        <div class="footer-brand">
          <img src="/assets/JTWC-white-192.png" alt="" class="footer-logo" />
          <div>
            <div class="footer-title">{{ org.identity.name }}</div>
            <div class="footer-tagline">{{ org.identity.footerTagline }}</div>
          </div>
        </div>

        <nav class="footer-col" aria-label="Footer navigation">
          <div class="footer-col__heading">Explore</div>
          <router-link
            v-for="link in navLinks"
            :key="link.to"
            :to="link.to"
            class="footer-link tap-target"
          >
            {{ link.label }}
          </router-link>
        </nav>

        <div class="footer-col">
          <div class="footer-col__heading">Connect</div>
          <!-- Only social accounts filled in in the config are rendered. -->
          <a
            v-for="social in socialLinks"
            :key="social.key"
            :href="social.url"
            target="_blank"
            rel="noopener"
            class="footer-link footer-link--social tap-target"
          >
            <svg viewBox="0 0 24 24" class="social-icon" aria-hidden="true">
              <path :d="social.svgPath" fill="currentColor" />
            </svg>
            {{ social.handle }}
          </a>
          <a :href="mailtoHref" class="footer-link tap-target">
            {{ org.contact.email }}
          </a>
          <router-link to="/admin" class="footer-link tap-target">Admin</router-link>
        </div>
      </div>

      <div class="page-shell footer-legal">
        {{ copyrightLine() }}
      </div>
    </footer>
  </q-layout>
</template>

<style scoped>
.site-header {
  background: var(--navy-800);
  color: #fff;
  box-shadow: 0 1px 0 rgba(255, 255, 255, 0.08), 0 6px 18px rgba(0, 21, 61, 0.18);
}

.site-toolbar {
  min-height: 64px;
  gap: 8px;
}

/* Brand ------------------------------------------------------------- */
.brand-link {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  color: #fff;
  text-decoration: none;
  min-width: 0;
}

.brand-link:hover {
  color: #fff;
}

.brand-logo {
  height: 38px;
  width: auto;
  display: block;
  flex: 0 0 auto;
}

.brand-text {
  display: flex;
  flex-direction: column;
  line-height: 1;
  min-width: 0;
}

.brand-text__main {
  font-family: var(--font-display);
  font-weight: 700;
  font-size: 1.32rem;
  text-transform: uppercase;
  letter-spacing: 0.02em;
}

.brand-text__sub {
  font-family: var(--font-display);
  font-weight: 600;
  font-size: 0.72rem;
  letter-spacing: 0.19em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.66);
  margin-top: 3px;
}

/* Desktop nav ------------------------------------------------------- */
.desktop-nav {
  display: flex;
  align-items: center;
  gap: 2px;
}

.nav-link {
  position: relative;
  padding: 0 12px;
  font-size: 0.83rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.76);
  border-radius: 6px;
}

.nav-link:hover {
  color: #fff;
  background: rgba(255, 255, 255, 0.08);
}

.nav-link--active {
  color: #fff;
}

.nav-link--active::after {
  content: '';
  position: absolute;
  left: 12px;
  right: 12px;
  bottom: 6px;
  height: 2px;
  background: #fff;
  border-radius: 2px;
}

.admin-btn {
  background: rgba(255, 255, 255, 0.12);
  color: #fff;
  border-radius: 8px;
  font-weight: 600;
  letter-spacing: 0.04em;
  min-height: 44px;
}

.admin-btn:hover {
  background: rgba(255, 255, 255, 0.2);
}

/* Drawer ------------------------------------------------------------ */
.drawer-head {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 20px 18px;
  background: var(--navy-800);
  color: #fff;
}

.drawer-logo {
  height: 42px;
  width: auto;
}

.drawer-head__main {
  font-family: var(--font-display);
  font-weight: 700;
  font-size: 1.3rem;
  text-transform: uppercase;
  line-height: 1;
}

.drawer-head__sub {
  font-family: var(--font-display);
  font-size: 0.7rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.66);
  margin-top: 4px;
}

.drawer-item {
  min-height: 52px;
  font-weight: 500;
  color: var(--grey-900);
  border-radius: 0 999px 999px 0;
  margin-right: 12px;
}

.drawer-item--active {
  background: var(--grey-100);
  color: var(--navy-800);
  font-weight: 600;
}

/* Footer ------------------------------------------------------------ */
.site-footer {
  background: var(--navy-900);
  color: rgba(255, 255, 255, 0.82);
  margin-top: var(--section-gap);
  padding: clamp(2rem, 5vw, 3rem) 0 1.25rem;
}

.footer-grid {
  display: grid;
  gap: clamp(1.5rem, 4vw, 2.5rem);
  grid-template-columns: 1fr;
}

@media (min-width: 700px) {
  .footer-grid {
    grid-template-columns: 1.6fr 1fr 1.3fr;
  }
}

.footer-brand {
  display: flex;
  align-items: center;
  gap: 12px;
}

.footer-logo {
  height: 52px;
  width: auto;
  flex: 0 0 auto;
}

.footer-title {
  font-family: var(--font-display);
  font-weight: 700;
  font-size: 1.25rem;
  text-transform: uppercase;
  color: #fff;
  line-height: 1.1;
}

.footer-tagline {
  font-size: 0.85rem;
  color: rgba(255, 255, 255, 0.62);
  margin-top: 4px;
}

.footer-col {
  display: flex;
  flex-direction: column;
}

.footer-col__heading {
  font-family: var(--font-display);
  font-weight: 600;
  font-size: 0.78rem;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.45);
  margin-bottom: 6px;
}

.footer-link {
  color: rgba(255, 255, 255, 0.82);
  font-size: 0.92rem;
  /* Long addresses must wrap rather than widen the page on small screens. */
  overflow-wrap: anywhere;
}

.footer-link:hover {
  color: #fff;
}

.footer-link--social {
  gap: 8px;
}

.social-icon {
  width: 15px;
  height: 15px;
  flex: 0 0 auto;
}

.footer-legal {
  margin-top: clamp(1.5rem, 4vw, 2.25rem);
  padding-top: 1rem;
  border-top: 1px solid rgba(255, 255, 255, 0.12);
  font-size: 0.8rem;
  color: rgba(255, 255, 255, 0.55);
}
</style>
