// =============================================================================
// ORGANIZATION DATA — DEFAULTS
// =============================================================================
// Everything about the club that appears on the site starts here. Edit this
// file, commit, and every page updates.
//
// Admins can also override these values from the dashboard, which writes to the
// Firestore document `settings/organization`. Precedence is:
//
//     Firestore override  >  this file
//
// A blank or missing override falls back to the value below, and "Reset to
// defaults" in the admin UI deletes the override document entirely. So this file
// remains both the seed and the safety net.
//
// Social accounts accept either a handle or a full URL:
//     x: 'CGJTWrestling'                      -> https://x.com/CGJTWrestling
//     x: '@CGJTWrestling'                     -> same (the @ is stripped)
//     x: 'https://x.com/some/custom/path'     -> used exactly as written
// Leave a social account as an empty string to hide it everywhere.
// =============================================================================

export interface OrganizationIdentity {
  /** Full display name. Used in the footer, page titles and copyright. */
  name: string
  /** Short form for tight spaces such as the admin header. */
  shortName: string
  /** The header/footer lockup renders these on two lines. */
  brandLine1: string
  brandLine2: string
  /** Large hero headline, also rendered on two lines. */
  heroLine1: string
  heroLine2: string
  /** Short phrase under the hero headline. */
  heroTagline: string
  /** Short phrase beside the footer logo. */
  footerTagline: string
}

export interface OrganizationContact {
  email: string
  /** Optional. Leave empty to hide the phone row on the contact page. */
  phone: string
}

export interface OrganizationLocation {
  /** One line per venue. Add or remove freely. */
  venues: string[]
  city: string
  state: string
}

export interface OrganizationSocial {
  x: string
  facebook: string
  instagram: string
  /**
   * Specific post URLs to embed, newest first.
   *
   * The profile-timeline embed and the single-post embed use different
   * pipelines at X. For this account the timeline pipeline returns HTTP 200
   * with an empty result set, while single posts render fine, so these are the
   * only reliable way to show anything.
   *
   * Caveat: an empty array from the admin form falls back to the defaults
   * below, because mergeSection treats an empty array as "not set". To show no
   * posts at all, clear the list here rather than in the dashboard.
   */
  featuredPosts: string[]
}

export interface OrganizationProgram {
  grades: string
  skillLevels: string
  seasonMonths: string
}

export interface OrganizationContent {
  /** Short teaser used in the About section on the home page. */
  aboutTeaser: string
  /** Longer intro at the top of the About page. */
  aboutIntro: string
  /** Bullet list on the About page. */
  offerings: string[]
  /** Values paragraph on the About page. */
  values: string
  /** Home page closing call to action. */
  ctaHeading: string
  ctaText: string
  /** Intro line on the contact page. */
  contactIntro: string
}

/** One row of the registration pricing table. */
export interface PricingTier {
  /** Stable key stored on registrations; keep it when renaming the label. */
  id: string
  label: string
  /** Whole dollars. */
  amount: number
  description: string
}

export interface OrganizationPayment {
  /** Zelle tag or enrolled email shown on the registration page. */
  zelleTag: string
  /**
   * Optional URL of the official QR image generated by your bank's app.
   * A scannable Zelle QR cannot be synthesised — the encoding is bank-issued —
   * so this is a paste-in field rather than something the app generates.
   */
  zelleQrImageUrl: string
  /** Payee line for cheques. */
  checkPayableTo: string
  /** Where cheques should be mailed, one line per entry. */
  mailingAddress: string[]
  /** Free text shown under the payment instructions. */
  instructions: string
  tiers: PricingTier[]
}

export interface OrganizationSettings {
  identity: OrganizationIdentity
  contact: OrganizationContact
  location: OrganizationLocation
  social: OrganizationSocial
  program: OrganizationProgram
  payment: OrganizationPayment
  content: OrganizationContent
}

export const defaultOrganization: OrganizationSettings = {
  identity: {
    name: 'Trojans Wrestling Club',
    shortName: 'Trojans',
    brandLine1: 'Trojans',
    brandLine2: 'Wrestling Club',
    heroLine1: 'Trojans',
    heroLine2: 'Wrestling Club',
    heroTagline: 'Building strength, discipline and champions.',
    footerTagline: 'Building champions on and off the mat',
  },

  contact: {
    email: 'admin@trojanswrestlingclub.com',
    phone: '',
  },

  location: {
    venues: [
      'Cary Grove Community Center',
      'District 26 Schools',
    ],
    city: 'Cary',
    state: 'IL',
  },

  social: {
    x: 'CaryTrojansWC',
    facebook: '',
    instagram: '',
    // Newest first. Admins can manage this list from the dashboard; it is
    // seeded here so the home page shows a post before anyone edits settings.
    featuredPosts: [
      'https://x.com/CaryTrojansWC/status/2091008347096912231',
    ],
  },

  program: {
    grades: 'K–8',
    skillLevels: 'All',
    seasonMonths: 'Nov–Feb',
  },

  payment: {
    zelleTag: '',
    zelleQrImageUrl: '',
    checkPayableTo: 'Trojans Wrestling Club',
    mailingAddress: [],
    instructions:
      'Include your registration reference code in the memo so we can match ' +
      'your payment to your registration.',
    tiers: [
      {
        id: 'early',
        label: 'Early Registration',
        amount: 0,
        description: 'Discounted rate before the season opens.',
      },
      {
        id: 'standard',
        label: 'Standard Registration',
        amount: 0,
        description: 'Regular season rate.',
      },
      {
        id: 'multi',
        label: 'Additional Wrestler',
        amount: 0,
        description: 'Reduced rate for each extra wrestler in the same family.',
      },
    ],
  },

  content: {
    aboutTeaser:
      'The Trojans Wrestling Club develops young athletes in the Cary Grove community ' +
      'through hard work, sportsmanship and a love for the sport. We welcome wrestlers ' +
      'of all experience levels.',
    aboutIntro:
      'The Trojans Wrestling Club serves young athletes in the Cary Grove area. Our ' +
      'mission is to teach the fundamentals of wrestling while instilling discipline, ' +
      'respect, hard work and teamwork.',
    offerings: [
      'Age-appropriate training for elementary and middle school wrestlers',
      'Experienced volunteer coaches focused on safety and development',
      'Participation in local dual meets and tournaments',
      'A positive, supportive environment for beginners and experienced wrestlers alike',
    ],
    values:
      'Every wrestler matters. We emphasize effort over outcome and personal growth ' +
      'over trophies. Parents and families are an essential part of our team.',
    ctaHeading: 'Ready to wrestle?',
    ctaText: 'New wrestlers and families are always welcome.',
    contactIntro:
      'Questions about the program, registration or volunteering? Reach out anytime.',
  },
}

// =============================================================================
// Below this line is wiring, not configuration. You should rarely need to edit
// it — only when adding support for a brand-new social platform.
//
// These are pure functions rather than precomputed constants, because live
// values can change at runtime when an admin edits the settings. The settings
// store calls them inside computed properties.
// =============================================================================

interface SocialPlatform {
  label: string
  baseUrl: string
  /** 24x24 viewBox path. Brand marks are inlined because the icon set bundled
   *  with this project (material-icons) contains no brand glyphs. */
  svgPath: string
}

/** Only the account handles; featuredPosts is not a linkable platform. */
type SocialPlatformKey = Exclude<keyof OrganizationSocial, 'featuredPosts'>

const SOCIAL_PLATFORMS: Record<SocialPlatformKey, SocialPlatform> = {
  x: {
    label: 'X',
    baseUrl: 'https://x.com/',
    svgPath:
      'M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68' +
      'l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z',
  },
  facebook: {
    label: 'Facebook',
    baseUrl: 'https://facebook.com/',
    svgPath:
      'M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987' +
      'h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46' +
      'h-1.253c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z',
  },
  instagram: {
    label: 'Instagram',
    baseUrl: 'https://instagram.com/',
    svgPath:
      'M12 2.163c3.204 0 3.584.012 4.85.07 1.366.062 2.633.336 3.608 1.311.975.975 1.249 2.242 ' +
      '1.311 3.608.058 1.266.07 1.646.07 4.85s-.012 3.584-.07 4.85c-.062 1.366-.336 2.633-1.311 ' +
      '3.608-.975.975-2.242 1.249-3.608 1.311-1.266.058-1.646.07-4.85.07s-3.584-.012-4.85-.07c-1.366' +
      '-.062-2.633-.336-3.608-1.311-.975-.975-1.249-2.242-1.311-3.608C2.175 15.584 2.163 15.204 ' +
      '2.163 12s.012-3.584.07-4.85c.062-1.366.336-2.633 1.311-3.608.975-.975 2.242-1.249 3.608' +
      '-1.311C8.416 2.175 8.796 2.163 12 2.163zm0 1.802c-3.15 0-3.503.012-4.74.068-.94.043-1.79' +
      '.208-2.36.778-.57.57-.735 1.42-.778 2.36-.056 1.237-.068 1.59-.068 4.74s.012 3.503.068 ' +
      '4.74c.043.94.208 1.79.778 2.36.57.57 1.42.735 2.36.778 1.237.056 1.59.068 4.74.068s3.503' +
      '-.012 4.74-.068c.94-.043 1.79-.208 2.36-.778.57-.57.735-1.42.778-2.36.056-1.237.068-1.59' +
      '.068-4.74s-.012-3.503-.068-4.74c-.043-.94-.208-1.79-.778-2.36-.57-.57-1.42-.735-2.36-.778' +
      '-1.237-.056-1.59-.068-4.74-.068zm0 3.063a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27z' +
      'm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 ' +
      '1.2 1.2 0 010-2.4z',
  },
}

export interface SocialLink {
  key: string
  /** Platform name, e.g. "X". */
  label: string
  /** Display text, e.g. "@CGJTWrestling". */
  handle: string
  /** Absolute profile URL. */
  url: string
  svgPath: string
}

/** Strips a leading @ or a full URL prefix, leaving the bare handle. */
function bareHandle(value: string): string {
  return value.trim().replace(/^https?:\/\/[^/]+\//i, '').replace(/^@/, '')
}

/**
 * Social accounts that have been filled in, ready to render.
 * Accepts a bare handle, an @handle, or a full URL.
 */
export function buildSocialLinks(social: OrganizationSocial): SocialLink[] {
  return (Object.keys(SOCIAL_PLATFORMS) as SocialPlatformKey[])
    .filter((key) => (social[key] ?? '').trim() !== '')
    .map((key) => {
      const platform = SOCIAL_PLATFORMS[key]
      const raw = social[key].trim()
      const isUrl = /^https?:\/\//i.test(raw)
      const handle = bareHandle(raw)

      return {
        key,
        label: platform.label,
        handle: `@${handle}`,
        url: isUrl ? raw : `${platform.baseUrl}${handle}`,
        svgPath: platform.svgPath,
      }
    })
}

/** The X handle without the @, for the embedded timeline widget. */
export function buildXHandle(social: OrganizationSocial): string {
  return bareHandle(social.x ?? '')
}

/** "Cary, IL" */
export function buildCityState(location: OrganizationLocation): string {
  return [location.city, location.state].filter(Boolean).join(', ')
}

/** Venue lines followed by the city/state, for address blocks. */
export function buildAddressLines(location: OrganizationLocation): string[] {
  return [...location.venues.filter(Boolean), buildCityState(location)].filter(Boolean)
}

/** `mailto:` href for the club address. */
export function buildMailtoHref(email: string): string {
  return `mailto:${email}`
}

/** "© 2026 Trojans Wrestling Club · Cary, IL" */
export function buildCopyrightLine(
  name: string,
  cityState: string,
  year: number = new Date().getFullYear(),
): string {
  return [`© ${year} ${name}`, cityState].filter(Boolean).join(' · ')
}

export default defaultOrganization
